version: '2.4'
services:
  database:
    image: postgres
    container_name: db_library
    environment:
      - POSTGRES_DB=library
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5431:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: